= Container Integration Configuration

NOTE: {editurl}container-integration.adoc[{editnote}]

== JBoss AS

////
TODO: JBoss AS 5, 7, Wildfly (Undertow)
////


mod_cluster is supported in AS7 via the modcluster subsystem See AS7 modcluster subsystem Configuration.

In other AS version mod_cluster's configuration resides within the
following file:

    $JBOSS_HOME/server/$PROFILE/deploy/mod_cluster.sar/META-INF/mod_cluster-jboss-beans.xml

The entry point for mod_cluster's server-side configuration is the `ModClusterListener` bean, which delegates web container
(e.g. JBoss Web) specific events to a container agnostic event handler.

In general, the `ModClusterListener` bean defines:

1. A `ContainerEventHandler` in which to handle events from the web container.
2. A reference to the JBoss mbean server.

e.g.

[source,xml]
----
<bean name="ModClusterListener" class="org.jboss.modcluster.container.jbossweb.JBossWebEventHandlerAdapter">
  <constructor>
    <parameter class="org.jboss.modcluster.container.ContainerEventHandler">
      <inject bean="ModClusterService"/>
    </parameter>
    <parameter class="javax.management.MBeanServer">
      <inject bean="JMXKernel" property="mbeanServer"/>
    </parameter>
  </constructor>
</bean>
----

=== Configuration Properties

The `ModClusterConfig` bean enumerates the configuration properties used by mod_cluster.
For the complete list of configuration properties and their default values, see the chapter entitled
Server-side Configuration Properties.

e.g.

[source,xml]
----
<bean name="ModClusterConfig" class="org.jboss.modcluster.config.ModClusterConfig" mode="On Demand">
  <!-- Specify configuration properties here -->
</bean>
----

=== Connectors

Like mod_jk and mod_proxy_balancer, mod_cluster requires a connector in your server.xml to which to forward web requests.
Unlike mod_jk and mod_proxy_balancer, mod_cluster is not confined to AJP, but can use HTTP as well. While AJP is generally
faster, an HTTP connector can optionally be secured via SSL. If multiple possible connectors are defined in your server.xml,
mod_cluster uses the following algorithm to choose between them:

. If an native (APR) AJP connector is available, use it.
. If an AJP connector is available, use it.
. Otherwise, choose the HTTP connector with the highest max threads.

=== Node Identity

Like mod_jk and mod_proxy_balancer, mod_cluster identifies each node via a unique
http://docs.jboss.org/jbossweb/2.1.x/config/engine.html[jvm route]. By default, mod_cluster uses the following algorithm to
assign the jvm route for a given node:

.  Use the value from `server.xml`, `<Engine jvmRoute="..."/>`, if defined.
.  Generate a jvm route using the configured TODO. The default implementation does the following:
    .  Use the value of the `jboss.mod_cluster.jvmRoute` system property, if defined.
    .  Generate a UUID.

While UUIDs are ideal for production systems, in a development or testing environment, it is useful to know which node served
a given request just by looking at the jvm route. In this case, you can utilize the `org.jboss.modcluster.SimpleJvmRouteFactory`.
The factory generates jvm routes of the form:

*bind-address*:*port*:*engine-name*

== JBoss Web & Tomcat

mod_cluster's entire configuration for JBoss Web or Tomcat resides entirely within `$CATALINA_HOME/conf/server.xml`.

This limits the adds the following constraints to mod_cluster's feature set:

* Only non-clustered mode is supported
* Only one load metric] can be used to calculate a load factor.

=== Lifecycle Listener

The entry point for JBoss Web and Tomcat configuration is the ModClusterListener.
All mod_cluster configuration properties are defined as
attributes of the `<Listener/>` element. For the complete list of configuration properties and their default values, see
the chapter entitled "Server-side Configuration Properties".

e.g.

[source,xml]
----
<Listener className="org.jboss.modcluster.container.catalina.standalone.ModClusterListener" advertise="true"/>
----

=== Additional Tomcat dependencies

mod_cluster uses jboss-logging, which exists in JBoss Web, but not in Tomcat. Consequently, to use mod_cluster with Tomcat,
it is necessary to add http://repository.jboss.org/nexus/content/groups/public-jboss/org/jboss/logging/jboss-logging-spi/[jboss-logging-spi.jar]
to `$CATALINA_HOME/lib`.

////
TODO: Removed migration guide from mod_cluster 1.0. Is it O.K.?
////


== AS7 modcluster subsystem Configuration

JBoss Application Server 7+ mod_cluster subsystem configuration.

////
TODO: Mention XSD and links to it.
////


=== ModCluster Subsystem in JBoss AS7

The mod_cluster integration is done via the modcluster subsystem.

=== ModCluster Subsystem minimal configuration

////
TODO: Explain better for uninitiated readers.
////


The minimal configuration is having the modcluster `schemaLocation` in the `schemaLocation` list:

[source,xml]
----
<extension module="org.jboss.as.modcluster"/>
----

and `subsystem` declaration like:

[source,xml]
----
<subsystem xmlns="urn:jboss:domain:modcluster:2.0"/>
----

////
TODO: Explain advertisement.
////


With that configuration modcluster will listen for advertise on `224.0.1.105:23364`.

== ModCluster Subsystem configuration

=== mod-cluster-config Attributes

////
TODO: Link. The attributes correspond to the properties
////


=== Proxy Discovery Configuration

////
TODO: Explain better the placement for Attributes and properties in their respective contexts.
////


[options="header"]
|===
| Attribute               | Property              | Default
| proxy-list              | proxyList             | *none*
| proxy-url               | proxyURL              | *none*
| advertise               | advertise             | *true*
| advertise-security-key  | advertiseSecurityKey  | *none*
| excluded-contexts       | excludedContexts      | *none*
| auto-enable-contexts    | autoEnableContexts    | *true*
| stop-context-timeout    | stopContextTimeout    | *10 seconds* (in seconds)
| socket-timeout          | nodeTimeout           | *20 seconds* (in milliseconds)
|===

=== Proxy Configuration

[options="header"]
|===
| Attribute              | Property             | Default
| sticky-session         | stickySession        | *true*
| sticky-session-remove  | stickySessionRemove  | *false*
| sticky-session-force   | stickySessionForce   | *true*
| node-timeout           | workerTimeout        | *-1*
| max-attempts           | maxAttempts          | *1*
| flush-packets          | flushPackets         | *false*
| flush-wait             | flushWait            | *-1*
| ping                   | ping                 | *10*
| smax                   | smax                 | *-1* (it uses default value)
| ttl                    | ttl                  | *-1* (it uses default value)
| domain                 | loadBalancingGroup   | *none*
| load-balancing-group   | loadBalancingGroup   | *none*
|===

=== SSL Configuration

////
TODO: SSL configuration part needs to be added here too
////


=== simple-load-provider Attributes

The simple load provider always sends the same load factor. Its purpose is testing, experiments and special scenarios such as hot stand-by.

////
TODO: Link to Hot Stand-by.
////

[source]
----
<subsystem xmlns="urn:jboss:domain:modcluster:1.0">
  <mod-cluster-config>
    <simple-load-provider factor="1"/>
  </mod-cluster-config>
</subsystem>
----

[options="header"]
|===
| Attribute  | Property            | Default
| factor     | LoadBalancerFactor  | 1
|===

=== dynamic-load-provider Attributes

The dynamic load provide allows to have `load-metric` as well as `custom-load-metric` defined. For example:

////
TODO: Check XSD for attributes and their descriptions.
////

[source,xml]
----
<subsystem xmlns="urn:jboss:domain:modcluster:1.0">
  <mod-cluster-config advertise-socket="mod_cluster">
    <dynamic-load-provider history="10" decay="2">
       <load-metric type="cpu" weight="2" capacity="1"/>
       <load-metric type="sessions" weight="1" capacity="512"/>
       <custom-load-metric class="mypackage.myclass" weight="1" capacity="512">
          <property name="myproperty" value="myvalue" />
          <property name="otherproperty" value="othervalue" />
       </custom-load-metric>
    </dynamic-load-provider>
  </mod-cluster-config>
</subsystem>
----

[options="header"]
|===
| Attribute  | Property     | Default
| history    | history      | 512
| decay      | decayFactor  | 512
|===

=== load-metric Configuration

The load-metric are the "classes" collecting information to allow computation of the load factor sent to httpd.

[options="header"]
|===
| Attribute  | Property                   | Default
| type       | A Server-Side Load Metric  | *mandatory*
| weight     | weight                     | *9*
| capacity   | capacity                   | *512*
|===

=== Out-of-box load metric types

[options="header"]
|===
| Type             | Corresponding Server-Side Load Metric
| cpu              | link:#average-system-load-metric[AverageSystem]
| mem              | link:#system-memory-usage-load-metric[SystemMemoryUsage] See https://issues.jboss.org/browse/MODCLUSTER-288[MODCLUSTER-288]
| heap             | link:#heap-memory-usage-load-metric[HeapMemoryUsage]
| sessions         | link:#active-sessions-load-metric[ActiveSessions]
| requests         | link:#request-count-load-metric[RequestCount]
| send-traffic     | link:#send-traffic-load-metric[SendTraffic]
| receive-traffic  | link:#receive-traffic-load-metric[ReceiveTraffic]
| busyness         | link:#busy-connectors-load-metric[BusyConnectors]
| connection-pool  | link:#connection-pool-usage-load-metric[ConnectionPoolUsage]
|===

=== custom-load-metric Configuration

The custom-load-metric are for user defined "classes" collecting information.
They are like the load-metric except `type` is replaced by `class`:

[options="header"]
|===
|Attribute  | Property            | Default
|class      | Name of your class  | *Mandatory*
|===

See an https://github.com/Karm/mod_cluster-custom-load-metric[Example Custom Load Metric] that reads load from a local file.

=== load-metric Configuration with the JBoss AS7 CLI

The load-metric have 4 commands to add / remove metrics

* add-metric: Allows to add a `load-metric` to the *dynamic-load-provider*, e.g.

    `./:add-metric(type=cpu, weight=2, capacity=1)`

* remove-metric: Allows to remove a `load-metric` from the *dynamic-load-provider*, e.g.

    ./:remove-metric(type=cpu)

* add-custom-metric: Allows to add a `load-custom-metric` to the *dynamic-load-provider*, e.g.

    ./:add-custom-metric(class=myclass, weight=2, capacity=1, \
    property=[("pool" => "mypool"), ("var" => "myvariable")])

* remove-custom-metric: Allows to remove a `load-custom-metric` from the *dynamic-load-provider*, e.g.

    ./:remove-custom-metric(class=myclass)

== Building worker-side Components

=== Requirements
Building mod_cluster's worker-side components from source requires the following tools:

* JDK 5.0+
* Maven 2.0+

=== Building

Steps to build:

. Download the mod_cluster sources

    git clone git://github.com/modcluster/mod_cluster.git

. Use maven "dist" profile to build:

    cd mod_cluster
    mvn -P dist package

**Note:** Some unit tests require UDP port 23365. Make sure your local firewall allows the port.
{: .notice}

=== Built Artifacts

The build produces the following output in the target directory:

* mod-cluster.sar
Exploded format sar to copy to the deploy dir in your JBoss AS install.

* JBossWeb-Tomcat/lib directory
Jar files to copy to the lib directory in your JBossWeb or Tomcat install to support use of mod_cluster.

* demo directory
The load balancing demo application.

////
TODO: Explain further, link.
////


* mod-cluster-XXX.tar.gz
The full distribution tarball; includes the aforementioned elements.

=== worker-side Configuration Properties

The tables below enumerate the configuration properties available to an application server node.
The location for these properties depends on how mod_cluster is configured.

==== Proxy Discovery Configuration

The list of proxies from which an application expects to receive AJP
connections is either defined statically, via the addresses defined in the proxyList
configuration property; or discovered dynamically via the advertise mechanism. Using a special mod_advertise
module, proxies can advertise their existence by periodically broadcasting a multicast message containing their address:port.
This functionality is enabled via the advertise configuration
property. If configured to listen, a server can learn of the proxy's existence, then notify that proxy of its
own existence, and update its configuration accordingly. This frees both the proxy *and* the server
from having to define static, environment-specific configuration values.

==== Session draining strategy

[options="header"]
|===
| Tomcat attribute        | AS7/Wildfly attribute     | Default       | Location | Scope    |
| sessionDrainingStrategy | session-draining-strategy | `DEFAULT` | Worker   | Worker   |
|===

Indicates the session draining strategy used during undeployment of a web application. There are three possible values:

* `DEFAULT`: Drain sessions before web application undeploy only if the web application is non-distributable.
* `ALWAYS`: Always drain sessions before web application undeploy, even for distributable web applications.
* `NEVER`: Do not drain sessions before web application undeploy, even for non-distributable web application.

==== Proxies

[options="header"]
|===
| Tomcat attribute        | AS7 attribute | Wildfly attribute | Default | Location | Scope    |
| proxyList               | proxy-list    | proxies           | *None*  | Worker   | Worker   |
|===

* Tomcat/AS7: Defines a comma delimited list of httpd proxies with which this node will initially communicate. Value should be of the form: *address1*:*port1*,*address2*:*port2*. Using the default configuration, this property can by manipulated via the jboss.mod_cluster.proxyList system property.
* Wildfly: In Wildfly, the `proxy-list` attribute of the modcluster subsystem element is deprecated. Instead, one uses an output socket binding. The following example leverages `jboss-cli.sh`, e.g. :
  * Add a socket binding: `/socket-binding-group=standard-sockets/remote-destination-outbound-socket-binding=my-proxies:add(host=10.10.10.11,port=3333)`
  * Add the socket binding to the modcluster subsystem: `/subsystem=modcluster/mod-cluster-config=configuration:write-attribute(name=proxies, value="my-proxies")`

==== Excluded contexts

[options="header"]
|===
| Tomcat attribute | AS7/Wildfly attribute  | Wildfly Default | Tomcat/AS7 Default | Location | Scope    |
| excludedContexts | excluded-contexts      | *None*          | ROOT, admin-console, invoker, bossws, jmx-console, juddi, web-console | Worker | Worker |
|===

List of contexts to exclude from httpd registration, of the form: *host1*:*context1*,*host2*:*context2*,*host3*:*context3*
If no host is indicated, it is assumed to be the default host of the server (e.g. localhost). "ROOT" indicates the root context. Using the default configuration, this property can by manipulated via the jboss.mod_cluster.excludedContexts system property.

==== Auto Enable Contexts

[options="header"]
|===
| Tomcat attribute   | AS7/Wildfly attribute  | Default | Location | Scope  |
| autoEnableContexts | auto-enable-contexts   | true    | Worker   | Worker |
|===

If false the contexts are registered disabled in httpd, they need to be enabled via the enable() mbean method, jboss-cli command or via mod_cluster_manager web console on Apache HTTP Server.

==== Stop context timeout

[options="header"]
|===
| Tomcat attribute   | AS7/Wildfly attribute  | Default | Location | Scope  |
| stopContextTimeout | stop-context-timeout   | 10 s    | Worker   | Worker |
|===

The amount of time in seconds for which to wait for a clean shutdown of a context (completion of pending requests for a distributable context; or destruction/expiration of active sessions for a non-distributable context).

==== Stop context timeout unit

[options="header"]
|===
| Tomcat attribute       | AS7/Wildfly attribute  | Default | Location | Scope  |
| stopContextTimeoutUnit | *None*                 | TimeUnit.SECONDS | Worker   | Worker |
|===

Tomcat allows for configuring an arbitrary TimeUnit for Stop context timeout

==== Proxy URL

[options="header"]
|===
| Tomcat attribute  | AS7/Wildfly attribute  | Default | Location | Scope  |
| proxyURL          | proxy-url              | /       | Worker   | Balancer |
|===

If defined, this value will be prepended to the URL of MCMP commands.

==== Socket timeout

[options="header"]
|===
| Tomcat attribute  | AS7/Wildfly attribute  | Default | Location | Scope  |
| socketTimeout     | socket-timeout         | 20 s    | Worker   | Worker |
|===

How long to wait for a response from an httpd proxy to MCMP commands before timing out, and flagging the proxy as in error.

==== Advertise

[options="header"]
|===
| Tomcat/AS7/Wildfly attribute  | Default                | Location | Scope  |
| advertise                     | true, if proxyList is undefined, false otherwise | Worker   | Worker |
|===

If enabled, httpd proxies will be auto-discovered via receiving multicast announcements.
This can be used either in concert or in place of a static proxies.

==== Advertise socket group

[options="header"]
|===
| Tomcat attribute       | AS7/Wildfly attribute  | Default     | Location | Scope  |
| advertiseGroupAddress  | advertise-socket       | 224.0.1.105 | Worker   | Worker |
| advertisePort          | in advertise-socket    | 23364       | Worker   | Worker |
|===

UDP multicast address:port on which to listen for httpd proxy multicast advertisements. Beware of the actual *interface* your
balancer/worker sends to/receives from. See https://issues.jboss.org/browse/MODCLUSTER-487[MODCLUSTER-487] for Apache HTTP Server behaviour
and https://issues.jboss.org/browse/MODCLUSTER-495[MODCLUSTER-495] for Tomcat's caveat.

==== Advertise security key

[options="header"]
|===
| Tomcat attribute     | AS7/Wildfly attribute  | Default | Location | Scope
| advertiseSecurityKey | advertise-security-key | *None*  | Worker   | Balancer
|===

If specified, httpd proxy advertisements checksums (using this value as a salt) will be required to be verified on the server side. This option *does not* secure your installation, it *does not* replace proper SSL configuration. It merely ensures that only certain workers can talk to certain balancers.
Beware of https://issues.jboss.org/browse/MODCLUSTER-446[MODCLUSTER-446].

==== Advertise thread factory

[options="header"]
|===
| Tomcat attribute       | AS7/Wildfly attribute  | Default | Location | Scope
| advertiseThreadFactory | *None*                 | Executors.defaultThreadFactory() | Worker | Worker
|===

The thread factory used to create the background advertisement listener.

==== JVMRoute factory

[options="header"]
|===
| Tomcat attribute       | AS7/Wildfly attribute  | Default | Location | Scope
| jvmRouteFactory        | *None*                 | new SystemPropertyJvmRouteFactory(new UUIDJvmRouteFactory(), "jboss.mod_cluster.jvmRoute") | Worker | Worker
|===

Defines the strategy for determining the jvm route of a node, if none was specified in Tomcat's server.xml.
The default factory first consults the `jboss.mod_cluster.jvmRoute` system property. If this system property is undefined, the jvm route is assigned a UUID.
Wildfly with Undertow web subsystem uses Undertow's `instance-id` or `jboss.mod_cluster.jvmRoute` system property or a UUID.

=== Proxy Configuration

The following configuration values are sent to proxies during server
startup, when a proxy is detected via the advertise mechanism, or during
the resetting of a proxy's configuration during error recovery.

[options="header"]
|===
| Attribute            | AS7 Attribute                | Default                            | Scope     | Description
| stickySession        | sticky-session               | true                               | Balancer  | Indicates whether subsequent requests for a given session should be routed to the same node, if possible.
| stickySessionRemove  | sticky-session-remove        | false                              | Balancer  | Indicates whether the httpd proxy should remove session stickiness in the event that the balancer is unable to route a request to the node to which it is stuck. This property is ignored if stickySession is false.
| stickySessionForce   | sticky-session-force         | false                              | Balancer  | Indicates whether the httpd proxy should return an error in the event that the balancer is unable to route a request to the node to which it is stuck. This property is ignored if stickySession is false.
| workerTimeout        | worker-timeout               | -1                                 | Balancer  | Number of seconds to wait for a worker to become available to handle a request. When no workers of a balancer are usable, mod_cluster will retry after a while (workerTimeout/100). That is timeout in the balancer mod_proxy documentation. A value of -1 indicates that the httpd will not wait for a worker to be available and will return an error if none is available.
| maxAttempts          | max-attempts                 | 1                                  | Balancer  | Maximum number of failover attempts before giving up. The minimum value is 0, i.e. no failover. The default value is 1, i.e. do a one failover attempt.
| flushPackets         | flush-packets                | false                              | Node      | Enables/disables packet flushing
| flushWait            | flush-wait                   | -1                                 | Node      | Time to wait before flushing packets in milliseconds. A value of -1 means wait forever.
| ping                 | ping                         | 10                                 | Node      | Time (in seconds) in which to wait for a pong answer to a ping
| smax                 | smax                         | Determined by httpd configuration  | Node      | Soft maximum idle connection count (that is the smax in worker mod_proxy documentation). The maximum value depends on the httpd thread configuration (ThreadsPerChild or 1).
| ttl                  | ttl                          | 60                                 | Node      | Time to live (in seconds) for idle connections above smax
| nodeTimeout          | node-timeout                 | -1                                 | Node      | Timeout (in seconds) for proxy connections to a node. That is the time mod_cluster will wait for the back-end response before returning error. That corresponds to timeout in the worker mod_proxy documentation. A value of -1 indicates no timeout. Note that mod_cluster always uses a cping/cpong before forwarding a request and the connectiontimeout value used by mod_cluster is the ping value.
| balancer             | balancer                     | mycluster                          | Node      | The balancer name
| loadBalancingGroup   | domain load-balancing-group  | *None*                             | Node      | If specified, load will be balanced among jvmRoutes withing the same load balancing group. A loadBalancingGroup is conceptually equivalent to a mod_jk domain directive. This is primarily used in conjunction with partitioned session replication (e.g. buddy replication).
|===


NOTE: When nodeTimeout is not defined the ProxyTimeout directive Proxy is
used. If ProxyTimeout is not defined the server timeout (Timeout) is
used (default 300 seconds). nodeTimeout, ProxyTimeout or Timeout is set
at the socket level.

==== SSL Configuration

The communication channel between application servers and httpd proxies
uses HTTP by default. This channel can be secured using HTTPS by setting
the ssl property to true.

NOTE: This HTTP/HTTPS channel should not be confused with the processing of HTTP/HTTPS client requests.

[options="header"]
|===
| Attribute                        | AS7 Attribute         | Default                                                          | Description
| ssl                              | *None*                | false                                                            | Should connection to proxy use a secure socket layer
| sslCiphers                       | cipher-suite          | *The default JSSE cipher suites*                                 | Overrides the cipher suites used to initialize an SSL socket ignoring any unsupported ciphers
| sslProtocol                      | protocol              | TLS (ALL in AS7)                                                 | Overrides the default SSL socket protocol.
| sslCertificateEncodingAlgorithm  | *None*                | *The default JSSE key manager algorithm*                         | The algorithm of the key manager factory
| sslKeyStore                      | certificate-key-file  | System.getProperty("user.home") + "/.keystore"          | The location of the key store containing client certificates
| sslKeyStorePassword              | password              | changeit                                                         | The password granting access to the key store (and trust store in AS7)
| sslKeyStoreType                  | *None*                | JKS                                                              | The type of key store
| sslKeyStoreProvider              | *None*                | *The default JSSE security provider*                             | The key store provider
| sslTrustAlgorithm                | *None*                | *The default JSSE trust manager algorithm*                       | The algorithm of the trust manager factory
| sslKeyAlias                      | key-alias             |                                                                  | The alias of the key holding the client certificates in the key store
| sslCrlFile                       | ca-revocation-url     |                                                                  | Certificate revocation list
| sslTrustMaxCertLength            | *None*                | 5                                                                | The maximum length of a certificate held in the trust store
| sslTrustStore                    | *None*                | javax.net.ssl.trustStorePassword  | The location of the file containing the trust store
| sslTrustStorePassword            | *None*                | javax.net.ssl.trustStore          | The password granting access to the trust store.
| sslTrustStoreType                | *None*                | javax.net.ssl.trustStoreType      | The trust store type
| sslTrustStoreProvider            | *None*                | javax.net.ssl.trustStoreProvider  | The trust store provider
|===

==== Load Configuration for JBoss Web and Tomcat

Additional configuration properties used when mod_cluster is configured
in JBoss Web standalone or Tomcat.

[options="header"]
|===
| Attribute           | Default | Description    |
| loadMetricClass     | org.jboss.modcluster.load.metric.impl.BusyConnectorsLoadMetric | Class name of an object implementing org.jboss.load.metric.LoadMetric
| loadMetricCapacity  | 1                                                              | The capacity of the load metric defined via the loadMetricClass property
| loadHistory         | 9                                                              | The number of historic load values to consider in the load balance factor computation.
| loadDecayFactor     | 2                                                              | The factor by which a historic load values should degrade in significance.
|===

== Worker-side Load Metrics

A major feature of mod_cluster is the ability to use server-side load
metrics to determine how best to balance requests.

The `DynamicLoadBalanceFactorProvider` bean computes the load
balance factor of a node from a defined set of load metrics.

[source,xml]
----
<bean name="DynamicLoadBalanceFactorProvider" class="org.jboss.modcluster.load.impl.DynamicLoadBalanceFactorProvider" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=LoadBalanceFactorProvider",exposedInterface=org.jboss.modcluster.load.impl.DynamicLoadBalanceFactorProviderMBean.class)</annotation>
  <constructor>
    <parameter>
      <set elementClass="org.jboss.modcluster.load.metric.LoadMetric">
        <inject bean="BusyConnectorsLoadMetric"/>
        <inject bean="HeapMemoryUsageLoadMetric"/>
      </set>
    </parameter>
  </constructor>
  <property name="history">9</property>
  <property name="decayFactor">2</property>
</bean>
----

Load metrics can be configured with an associated weight and capacity.

The weight (default is 1) indicates the significance of a metric with
respect to the other metrics. For example, a metric of weight 2 will
have twice the impact on the overall load factor than a metric of weight
1.

The capacity of a metric serves 2 functions:

-   To normalize the load values from each metric. In some load metrics,
    capacity is already reflected in the load values. The capacity of a
    metric should be configured such that `0 \<= (load / capacity) \>= 1`.

-   To favor some nodes over others. By setting the metric capacities to
    different values on each node, proxies will effectively favor nodes
    with higher capacities, since they will return smaller load values.
    This adds an interesting level of granularity to node weighting.
    Consider a cluster of two nodes, one with more memory, and a second
    with a faster CPU; and two metrics, one memory-based and the other
    CPU-based. In the memory-based metric, the first node would be given
    a higher load capacity than the second node. In a CPU-based metric,
    the second node would be given a higher load capacity than the first
    node.

Each load metric contributes a value to the overall load factor of a
node. The load factors from each metric are aggregated according to
their weights.

In general, the load factor contribution of given metric is: `(load /
capacity) \* weight / total weight`.

The DynamicLoadBalanceFactorProvider applies a time decay function to
the loads returned by each metric. The aggregate load, with respect to
previous load values, can be expressed by the following formula:

+++L = (L<sub>0</sub>/D<sup>0</sup> + L <sub>1</sub>/D<sup>1</sup> + L<sub>2</sub>/D<sup>2</sup> + L<sub>3</sub>/D<sup>3</sup> + ... + L<sub>H</sub>/D<sup>H</sup>) / (1/D<sup>0</sup> + 1/D<sup>1</sup> + 1/D<sup>2</sup> + 1/D<sup>3</sup> + ... 1/D<sup>H</sup>)+++

... or more concisely as:

+++L = (∑<sup>H</sup><sub>i=0</sub> L<sub>i</sub>/D<sup>i</sup>) / (∑<sup>H</sup><sub>i=0</sub> 1/D<sup>i</sup>)+++

... where D = decayFactor, and H = history.

Setting history = 0 effectively disables the time decay function and
only the current load for each metric will be considered in the load
balance factor computation.

The mod_cluster load balancer expects the load factor to be an integer
between 0 and 100, where 0 indicates max load and 100 indicates zero
load. Therefore, the final load factor sent to the load balancer

+++L<sub>Final</sub> = 100 - (L \* 100)+++

While you are free to write your own load metrics, the following
LoadMetrics are available out of the box:

=== Web Container metrics

[[active-sessions-load-metric]]
==== Active Sessions Load Metric

* Requires an explicit capacity
* Uses `SessionLoadMetricSource` to query session managers
* Analogous to method=S in mod_jk

e.g., with JBoss AS 5:

[source,xml]
----
<bean name="ActiveSessionsLoadMetric" class="org.jboss.modcluster.load.metric.impl.ActiveSessionsLoadMetric" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=ActiveSessionsLoadMetric",exposedInterface=org.jboss.modcluster.load.metric.LoadMetricMBean.class)</annotation>
  <constructor>
    <parameter><inject bean="SessionLoadMetricSource"/></parameter>
  </constructor>
  <property name="capacity">1000</property>
</bean>
<bean name="SessionLoadMetricSource" class="org.jboss.modcluster.load.metric.impl.SessionLoadMetricSource" mode="On Demand">
  <constructor>
    <parameter class="javax.management.MBeanServer">
      <inject bean="JMXKernel" property="mbeanServer"/>
    </parameter>
  </constructor>
</bean>
----

[[busy-connectors-load-metric]]
==== Busy Connectors Load Metric

* Returns the percentage of connector threads from the thread pool that are busy servicing requests
* Uses `ThreadPoolLoadMetricSource` to query connector thread
* Analogous to `method=B` in mod_jk
* https://github.com/modcluster/mod_cluster/blob/master/core/src/main/java/org/jboss/modcluster/load/metric/impl/BusyConnectorsLoadMetric.java[BusyConnectorsLoadMetric.java]

e.g., with JBoss AS 5:

[source,xml]
----
<bean name="BusyConnectorsLoadMetric" class="org.jboss.modcluster.load.metric.impl.BusyConnectorsLoadMetric" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=BusyConnectorsLoadMetric",exposedInterface=org.jboss.modcluster.load.metric.LoadMetricMBean.class)</annotation>
  <constructor>
    <parameter><inject bean="ThreadPoolLoadMetricSource"/></parameter>
  </constructor>
</bean>
<bean name="ThreadPoolLoadMetricSource" class="org.jboss.modcluster.load.metric.impl.ThreadPoolLoadMetricSource" mode="On Demand">
  <constructor>
    <parameter class="javax.management.MBeanServer">
      <inject bean="JMXKernel" property="mbeanServer"/>
    </parameter>
  </constructor>
</bean>
----

[[receive-traffic-load-metric]]
==== Receive Traffic Load Metric

* Returns the incoming request POST traffic in KB/sec (the application needs to read POST data)
* Requires an explicit capacity
* Uses `RequestProcessorLoadMetricSource` to query request processors
* Analogous to `method=T` in mod_jk

e.g., with JBoss AS 5:

[source,xml]
----
<bean name="ReceiveTrafficLoadMetric" class="org.jboss.modcluster.load.metric.impl.ReceiveTrafficLoadMetric" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=ReceiveTrafficLoadMetric",exposedInterface=org.jboss.modcluster.load.metric.LoadMetricMBean.class)</annotation>
  <constructor>
    <parameter class="org.jboss.modcluster.load.metric.impl.RequestProcessorLoadMetricSource">
      <inject bean="RequestProcessorLoadMetricSource"/>
    </parameter>
  </constructor>
  <property name="capacity">1024</property>
</bean>
<bean name="RequestProcessorLoadMetricSource" class="org.jboss.modcluster.load.metric.impl.RequestProcessorLoadMetricSource" mode="On Demand">
  <constructor>
    <parameter class="javax.management.MBeanServer">
      <inject bean="JMXKernel" property="mbeanServer"/>
    </parameter>
  </constructor>
</bean>
----

[[send-traffic-load-metric]]
==== Send Traffic Load Metric

* Returns the outgoing request traffic in KB/sec
* Requires an explicit capacity
* Uses `RequestProcessorLoadMetricSource` to query request processors
* Analogous to method=T in mod_jk

e.g., with JBoss AS 5:

[source,xml]
----
<bean name="SendTrafficLoadMetric" class="org.jboss.modcluster.load.metric.impl.SendTrafficLoadMetric" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=SendTrafficLoadMetric",exposedInterface=org.jboss.modcluster.load.metric.LoadMetricMBean.class)</annotation>
  <constructor>
    <parameter class="org.jboss.modcluster.load.metric.impl.RequestProcessorLoadMetricSource">
      <inject bean="RequestProcessorLoadMetricSource"/>
    </parameter>
  </constructor>
  <property name="capacity">512</property>
</bean>
----

==== Request Count Load Metric

* Returns the number of requests/sec
* Requires an explicit capacity
* Uses `RequestProcessorLoadMetricSource` to query request processors
* Analogous to `method=R` in mod_jk

e.g., with JBoss AS 5:

[source,xml]
----
<bean name="RequestCountLoadMetric" class="org.jboss.modcluster.load.metric.impl.RequestCountLoadMetric" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=RequestCountLoadMetric",exposedInterface=org.jboss.modcluster.load.metric.LoadMetricMBean.class)</annotation>
  <constructor>
    <parameter class="org.jboss.modcluster.load.metric.impl.RequestProcessorLoadMetricSource">
      <inject bean="RequestProcessorLoadMetricSource"/>
    </parameter>
  </constructor>
  <property name="capacity">1000</property>
</bean>
----

=== System/JVM metrics

==== Average System Load Metric

* Returns CPU load
* Requires Java 1.6+
* Uses `OperatingSystemLoadMetricSource` to generically read attributes
* Is not available on Windows
* https://github.com/modcluster/mod_cluster/blob/master/core/src/main/java/org/jboss/modcluster/load/metric/impl/AverageSystemLoadMetric.java[AverageSystemLoadMetric.java]

e.g., with JBoss AS 5:

[source,xml]
----
<bean name="AverageSystemLoadMetric" class="org.jboss.modcluster.load.metric.impl.AverageSystemLoadMetric" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=AverageSystemLoadMetric",exposedInterface=org.jboss.modcluster.load.metric.LoadMetricMBean.class)</annotation>
  <constructor>
    <parameter><inject bean="OperatingSystemLoadMetricSource"/></parameter>
  </constructor>
</bean>
<bean name="OperatingSystemLoadMetricSource" class="org.jboss.modcluster.load.metric.impl.OperatingSystemLoadMetricSource" mode="On Demand">
</bean>
----

[[heap-memory-usage-load-metric]]
==== Heap Memory Usage Load Metric

* Returns the heap memory usage as a percentage of max heap size

e.g., with JBoss AS 5:

[source,xml]
----
<bean name="HeapMemoryUsageLoadMetric" class="org.jboss.modcluster.load.metric.impl.HeapMemoryUsageLoadMetric" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=HeapMemoryUsageLoadMetric",exposedInterface=org.jboss.modcluster.load.metric.LoadMetricMBean.class)</annotation>
</bean>
----

=== Other metrics

[[connection-pool-usage-load-metric]]
==== ConnectionPoolUsageLoadMetric

* Returns the percentage of connections from a connection pool that are in use
* Uses ConnectionPoolLoadMetricSource to query JCA connection pools

e.g., with JBoss AS 5:

[source,xml]
----
<bean name="ConnectionPoolUsageMetric" class="org.jboss.modcluster.load.metric.impl.ConnectionPoolUsageLoadMetric" mode="On Demand">
  <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="jboss.web:service=ConnectionPoolUsageLoadMetric",exposedInterface=org.jboss.modcluster.load.metric.LoadMetricMBean.class)</annotation>
  <constructor>
    <parameter><inject bean="ConnectionPoolLoadMetricSource"/></parameter>
  </constructor>
</bean>
<bean name="ConnectionPoolLoadMetricSource" class="org.jboss.modcluster.load.metric.impl.ConnectionPoolLoadMetricSource" mode="On Demand">
  <constructor>
    <parameter class="javax.management.MBeanServer">
      <inject bean="JMXKernel" property="mbeanServer"/>
    </parameter>
  </constructor>
</bean>
----

== Installing Worker-side Components

First, extract the server-side binary to a temporary directory. The
following assumes it was extracted to /tmp/mod_cluster

Your next step depends on whether your target server is JBoss AS or
JBossWeb/Tomcat.

=== Installing in JBoss AS 6.0.0.M1 and up

You don't need to do anything to install the java-side binaries in AS
6.x; it's part of the AS distribution's default, standard and all
configurations.

=== Installing in JBoss AS 5.x

Assuming \$JBOSS_HOME indicates the root of your JBoss AS install and
that you want to use mod_cluster in the AS's all config:

[source,bash]
----
cp -r /tmp/mod_cluster/mod_cluster.sar $JBOSS_HOME/server/all/deploy
----

=== Installing in Tomcat

Assuming `$CATALINA_HOME` indicates the root of your Tomcat install:

[source,bash]
----
cp /tmp/mod_cluster/JBossWeb-Tomcat/lib/jboss-logging.jar $CATALINA_HOME/lib/
cp /tmp/mod_cluster/JBossWeb-Tomcat/lib/mod_cluster-container-catalina* $CATALINA_HOME/lib/
cp /tmp/mod_cluster/JBossWeb-Tomcat/lib/mod_cluster-container-spi* $CATALINA_HOME/lib/
cp /tmp/mod_cluster/JBossWeb-Tomcat/lib/mod_cluster-core* $CATALINA_HOME/lib/
----

and additionally for Tomcat6:

[source,bash]
----
cp /tmp/mod_cluster/JBossWeb-Tomcat/lib/mod_cluster-container-tomcat6* $CATALINA_HOME/lib
----

and additionally for Tomcat7:

[source,bash]
----
cp /tmp/mod_cluster/JBossWeb-Tomcat/lib/mod_cluster-container-tomcat7* $CATALINA_HOME/lib
----


