[[overview]]
= Overview

NOTE: {editurl}introduction.adoc[{editnote}]

mod_cluster is an httpd-based load balancer. Like mod_jk and
mod_proxy, mod_cluster uses a communication channel to forward
requests from httpd to one of a set of application server nodes. Unlike
mod_jk and mod_proxy, mod_cluster leverages an additional connection
between the application server nodes and httpd. The application server
nodes use this connection to transmit server-side load balance factors
and lifecycle events back to httpd via a custom set of HTTP methods,
affectionately called the Mod-Cluster Management Protocol (MCMP). This
additional feedback channel allows mod_cluster to offer a level of
intelligence and granularity not found in other load balancing
solutions.

Within httpd, mod_cluster is implemented as a set of modules for httpd
with mod_proxy enabled. Much of the logic comes from mod_proxy, e.g.
mod_proxy_ajp provides all the AJP logic needed by mod_cluster.

[[platforms]]
== Platforms

JBoss already prepares http://www.jboss.org/mod_cluster/downloads.html[binary
packages] with httpd
and mod_cluster so you can quickly try mod_cluster on the following
platforms:

* Linux x86, x64, ia64
* Solaris x86, SPARC
* Windows x86, x64, ia64

[[advantages]]
== Advantages
mod_cluster boasts the following advantages over other httpd-based load balancers:

* Dynamic configuration of httpd workers

Traditional httpd-based load balancers require explicit configuration of the workers available to a proxy. In mod_cluster, the bulk of the proxy's configuration resides on the application servers. The set of proxies to which an application server will communicate is determined either by a static list or using dynamic discovery via the advertise mechanism. The application server relays lifecycle events (e.g. server startup/shutdown) to the proxies allowing them to effectively auto-configure themselves. Notably, the graceful shutdown of a server will not result in a failover response by a proxy, as is the case with traditional httpd-based load balancers.

* Server-side load balance factor calculation

In contrast with traditional httpd-based load balancers, mod_cluster uses load balance factors calculated and provided by the application servers, rather than computing these in the proxy. Consequently, mod_cluster offers a more robust and accurate set of load metrics than is available from the proxy. (see Load Metrics for more)

* Fine grained web-app lifecycle control

Traditional httpd-based load balancers do not handle web application undeployments particularly well. From the proxy's perspective requests to an undeployed web application are indistinguishable from a request for an non-existent resource, and will result in 404 errors. In mod_cluster, each server forwards any web application context lifecycle events (e.g. web-app deploy/undeploy) to the proxy informing it to start/stop routing requests for a given context to that server.

* AJP is optional

Unlike mod_jk, mod_cluster does not require AJP. httpd connections to application server nodes can use HTTP, HTTPS, or AJP.
The original concepts are described in a http://www.jboss.org/community/docs/DOC-11431[wiki].

== Requirements

=== Balancer side

* Apache HTTP Server 2.2.15+ (legacy 2.2.8+)

=== Worker side

mod_cluster java module is provided for all the undermentioned containers:

* Tomcat 6
* Tomcat 7
* Tomcat 8
* JBoss AS7+
* Wildfly

== Limitations

mod_cluster uses shared memory to keep the nodes description, the shared memory is created at the start of httpd and the structure of each item is fixed. The following cannot be changed by configuration directives.

* Max Alias length 40 characters (Host: hostname header, Alias in&lt;Host/&gt;).
* Max context length 40 (for example myapp.war deploys in /myapp/myapp is the context).
* Max balancer name length 40 (balancer property in mbean).
* Max JVMRoute string length 80 (JVMRoute in &lt;Engine/&gt;).
* Max load balancing group name length 20 (domain property in mbean).
* Max hostname length for a node 64 (address in the &lt;Connector/&gt;).
* Max port length for a node 7 (8009 is 4 characters, port in the &lt;Connector/&gt;).
* Max scheme length for a node 6 (possible values are http, https, ajp, liked with the protocol of &lt;Connector/&gt;).
* Max cookie name 30 (the header cookie name for sessionid default value: JSESSIONID from org.apache.catalina.Globals.SESSION_COOKIE_NAME).
* Max path name 30 (the parameter name for the sessionid default value: jsessionid from org.apache.catalina.Globals.SESSION_PARAMETER_NAME).
* Max length for a sessionid 120 (something like BE81FAA969BF64C8EC2B6600457EAAAA.node01).

== Downloads

Download the latest http://mod-cluster.jboss.org/downloads[mod_cluster release].

The release is comprised of the following artifacts:

* httpd binaries for common platforms
* Wildfly/JBoss AS/JBossWeb/Tomcat Java distribution

Alternatively, you can build from source using the https://github.com/modcluster/mod_cluster[mod_cluster git repository] and https://github.com/modcluster/mod_proxy_cluster[mod_proxy_cluster git repository].

== Configuration

If you want to skip the details and just set up a minimal working
installation of mod_cluster, see the link:#Quick_Start_Guide[Quick Start Guide].

* Configuring link:#balancer_config[balancer]
* Configuring link:#worker_config[workers]

== Migration

Migrating from mod_jk or mod_proxy is fairly straightforward. In general, much of the configuration previously
found in httpd.conf is now defined in the application server worker nodes.

* Migrating from link:#migration-from-modjk[mod_jk]
* Migrating from link:#migration-from-modproxy[mod_proxy]

== SSL support

Both the request connections between httpd and the application server nodes, and the feedback channel
between the nodes and httpd can be secured. The former is achieved via the link:#mod_proxy_https[mod_proxy_https module]
and a corresponding ssl-enabled HTTP connector in JBoss Web or Undertow. The latter requires the
link:#UsingSSL[mod_ssl module] and link:#worker_config[explicit configuration in JBoss AS/Web/Undertow].

mod_cluster contains mod_ssl, therefore the warning (copied from OpenSSL https://www.openssl.org/[web page]).

WARNING: Strong cryptography: Please remember that export/import and/or use of strong cryptography software, providing cryptography hooks, or even just communicating technical details about cryptography software is illegal in some parts of the world. So when you import this package to your country, re-distribute it from there or even just email technical suggestions or even source patches to the authors or other people you are strongly advised to pay close attention to any laws or regulations which apply to you. The authors of openssl are not liable for any violations you make here. So be careful, it is your responsibility.

