[[httpd]]
= httpd configuration

NOTE: {editurl}native.adoc[{editnote}]

== Apache httpd configuration

You need to load the modules that are needed for mod_cluster for example:

[source]
----
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
LoadModule cluster_slotmem_module modules/mod_cluster_slotmem.so
LoadModule manager_module modules/mod_manager.so
LoadModule proxy_cluster_module modules/mod_proxy_cluster.so
LoadModule advertise_module modules/mod_advertise.so
----

NOTE: *mod_cluster 1.2.x vs mod_cluster 1.3.x:* Note that from mod_cluster 1.3.x on, the slotmem module is called
`LoadModule cluster_slotmem_module modules/mod_cluster_slotmem.so` instead of former `LoadModule slotmem_module modules/mod_slotmem.so`.

mod_proxy and mod_proxy_ajp are standard httpd modules. mod_slotmem is a shared slotmem memory provider.
mod_manager is the module that reads information from JBoss AS/JBossWeb/Tomcat and updates the shared memory
information. mod_proxy_cluster is the module that contains the balancer for mod_proxy. mod_advertise is an
additional module that allows httpd to advertise via multicast packets the IP and port where the mod_cluster
is listening. This multi-module architecture allows the modules to easily be changed depending on what the
customer wants to do.

For example when using http instead of AJP, only

[source]
----
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
----

needs to be changed to:

[source]
----
LoadModule proxy_http_module modules/mod_proxy_http.so
----

== mod_proxy configuration

mod_proxy directives like ProxyIOBufferSize could be used to configure mod_cluster. There is no need to use ProxyPass
directives because mod_cluster automatically configures which URLs have to be forwarded to JBossWEB.

== mod_slotmem/cluster_slotmem_module configuration

The actual version does not require any configuration directives.

== mod_proxy_cluster

=== CreateBalancers

CreateBalancers define how balancers are created in the httpd VirtualHosts, this is to allow directives like:

[source]
----
ProxyPass / balancer://mycluster1/[balancer://mycluster1/]
----

* 0 &mdash; Create in all VirtualHosts defined in httpd.

* 1 &mdash; Don't create balancers (requires at least one ProxyPass/ProxyPassMatch to define the balancer names).

* 2 &mdash; Create only the main server.

*Default:* 0

*CreateBalancers 1:* When using 1 don't forget to configure the balancer in the ProxyPass directive, because the default is
empty stickysession and `nofailover=Off` and the values received via the MCMP CONFIG message are ignored.
{: .notice}

*Default: 0* Note https://issues.jboss.org/browse/MODCLUSTER-430[MODCLUSTER-430 &mdash; CreateBalancers behave the same with option 0 or 2]
{: .notice}

=== UseAlias

Check that the Alias corresponds to the ServerName (See http://labs.jboss.com/file-access/default/members/jbossweb/freezone/docs/latest/config/host.html[Host Name Aliases]).

* Off &mdash; Don't check (ignore Aliases)
* On &mdash; Check aliases

*Default:* Off Ignore the Alias information from the nodes.

*Older mod_cluster versions:* Versions older than 1.3.1.Final only accept values 0 and 1 respectively.
{: .notice}

=== LBstatusRecalTime
Time interval in seconds for loadbalancing logic to recalculate the status of a node.

*Default:* 5 seconds

The actual formula to recalculate the status of a node is:

[source]
----
status = lbstatus + (elected - oldelected) * 1000)/lbfactor;
----

lbfactor is received for the node via STATUS messages.lbstatus is recalculated every LBstatusRecalTime seconds using the formula:
`lbstatus = (elected - oldelected) * 1000)/lbfactor`

elected is the amount of time the worker has been elected. `oldelected` is `elected` last time the `lbstatus`
was recalculated. The node with the lowest `status` is selected. Nodes with `lbfactor ≤ 0` are skipped by the both
calculation logics.

=== WaitForRemove

Time in seconds before a removed node is forgotten by httpd.

**Default:** 10 seconds

=== ProxyPassMatch/ProxyPass

ProxyPassMatch and ProxyPass are mod_proxy directives that when using `!` (instead the back-end url) prevent to
reverse-proxy in the path. This could be used allow httpd to serve static information like images.

[source]
----
ProxyPassMatch ^(/.*\.gif)$ !
----

The above for example will allow httpd to server directly the .gif files.

=== EnableOptions

Use `OPTIONS` method to periodically check the active connection. Fulfils the same role as the `CPING/CPONG` used by AJP
but for HTTP/HTTPS connections. The endpoint needs to implement at least HTTP/1.1.

 * On (or no value) &mdash; Use OPTIONS
 * Off &mdash; Don't use OPTIONS

**Default:** On

== mod_manager

The Context of a mod_manger directive is VirtualHost except mentioned otherwise. **server config** means that it must be outside a
VirtualHost configuration. If not an error message will be displayed and httpd will not start.

=== EnableMCPMReceive

EnableMCPMReceive &mdash; allow the VirtualHost to receive Mod Cluster Protocol Messages (MCPM). You need one
EnableMCPMReceive in your httpd configuration to allow mod_cluster to
work, put it in the VirtualHost where you configure advertise.

This directive was added so as to address the issue of receiving MCPM on arbitrary VirtualHosts which was problematic due to accepting messages on insecure, unintended VirtualHosts.

=== MemManagerFile

That is the base name for the names mod_manager will use to store configuration, generate keys for shared memory or lock
files. That must be an absolute path name; the directories will created if needed. It is highly recommended that those
files are placed on a local drive and not an NFS share. (Context: **server config**)

**Default:** `$server_root/logs/`
<script src="http://gist-it.appspot.com/github/modcluster/mod_cluster/blob/master/native/mod_manager/mod_manager.c?slice=521:538&footer=minimal"></script>

=== Maxcontext

The maximum number of application contexts supported by mod_cluster. (Context: **server config**)

**Default:**
<script src="http://gist-it.appspot.com/github/modcluster/mod_cluster/blob/master/native/mod_manager/mod_manager.c?slice=55:56&footer=minimal"></script>

=== Maxnode

That is the maximum number of nodes supported by mod_cluster. (Context: **server config**)

**Default:**
<script src="http://gist-it.appspot.com/github/modcluster/mod_cluster/blob/master/native/mod_manager/mod_manager.c?slice=56:57&footer=minimal"></script>

=== Maxhost

That is the maximum number of hosts (Aliases) supported by mod_cluster. That is also the max number of balancers. (Context: **server config**)

**Default:**
<script src="http://gist-it.appspot.com/github/modcluster/mod_cluster/blob/master/native/mod_manager/mod_manager.c?slice=57:58&footer=minimal"></script>

=== Maxsessionid

////
TODO
////

Maxsessionid: That is the number of active sessionid we store to give
number of active sessions in the mod_cluster-manager handler. A session
is unactive when mod_cluster doesn't receive any information from the
session in 5 minutes. (Context: server config)

Default: 0 (the logic is not activated).

=== MaxMCMPMaxMessSize

MaxMCMPMaxMessSize: Maximum size of MCMP messages. from other Max
directives.

Default: calculated from other Max directives. Min: 1024

=== ManagerBalancerName

ManagerBalancerName: That is the name of balancer to use when the JBoss
AS/JBossWeb/Tomcat doesn't provide a balancer name.

Default: mycluster

=== PersistSlots

PersistSlots: Tell mod_slotmem to persist the nodes, Alias and Context
in files. (Context: server config)

Default: Off

=== CheckNonce

CheckNonce: Switch check of nonce when using mod_cluster-manager
handler on | off Since 1.1.0.CR1

Default: on Nonce checked

=== AllowDisplay

AllowDisplay: Switch additional display on mod_cluster-manager main
page on | off Since 1.1.0.GA

Default: off Only version displayed

=== AllowCmd

AllowCmd: Allow commands using mod_cluster-manager URL on | off Since
mod_cluster 1.1.0.GA

Default: on Commmands allowed

=== ReduceDisplay

ReduceDisplay - Reduce the information the main mod_cluster-manager
page to allow more nodes in the page. on | off

Default: off Full information displayed

=== SetHandler mod_cluster-manager

SetHandler mod_cluster-manager: That is the handler to display the node
mod_cluster sees from the cluster. It displays the information about
the nodes like INFO and additionally counts the number of active
sessions.

[source]
----
\# httpd 2.2.x and older
<Location /mod_cluster_manager>
   SetHandler mod_cluster-manager
   Order deny,allow
   Deny from all
   Allow from 127.0.0.1
</Location>

\# httpd 2.4.x and on
<Location /mod_cluster_manager>
   SetHandler mod_cluster-manager
   Require ip 127.0.0
</Location>
----

When accessing the location you define in httpd.conf you get something
like:

////
TODO: Add pic
////


Note that:

Transferred: Corresponds to the POST data send to the back-end server.

Connected: Corresponds to the number of requests been processed when the
mod_cluster status page was requested.

sessions: Corresponds to the number of sessions mod_cluster report as
active (on which there was a request during the past 5 minutes). That
field is not present when Maxsessionid is zero.

=== mod_advertise

mod_advertise uses multicast packets to advertise the VirtualHost where it is configured that must be the same VirtualHost
where mod_manager is defined. Of course at least one mod_advertise must be in the VirtualHost to allow mod_cluster to find
the right IP and port to give to the ClusterListener.

=== ServerAdvertise

ServerAdvertise On: Use the advertise mechanism to tell the JBoss
AS/JBossWeb/Tomcat to whom it should send the cluster information.

ServerAdvertise On http://hostname:port: Tell the hostname and port to use. Only needed if the VirtualHost is not defined
correctly, if the VirtualHost is a http://httpd.apache.org/docs/2.2/vhosts/name-based.html[Name-based Virtual Host] or when
VirtualHost is not used.

ServerAdvertise Off: Don't use the advertise mechanism.

Default: Off. (Any Advertise directive in a VirtualHost sets it to On in
the VirtualHost)

=== AdvertiseGroup

AdvertiseGroup IP:port: That is the multicast address to use (something like 232.0.0.2:8888 for example).
IP should correspond to AdvertiseGroupAddress and port to AdvertisePort in the JBoss AS/JBossWeb/Tomcat configuration.
Note that if JBoss AS is used and the -u startup switch is included in the AS startup command, the default AdvertiseGroupAddress
is the value passed via the -u. If port is missing the default port will be used: 23364.

Default: 224.0.1.105:23364.

=== AdvertiseFrequency

AdvertiseFrequency seconds[.miliseconds]: Time between the multicast
messages advertising the IP and port.

Default: 10 Ten seconds.

=== AdvertiseSecurityKey

AdvertiseSecurityKey value: key string used to verify advertisements checksums. If configured on either side the verification
is required. Both sides must use the same security key.

Default: No default value.

=== AdvertiseManagerUrl

AdvertiseManagerUrl value: Not used in this version (It is sent in the X-Manager-Url: value header). That is the URL that
JBoss AS/JBossWeb/Tomcat should use to send information to mod_cluster

Default: No default value. Information not sent.

=== AdvertiseBindAddress

AdvertiseBindAddress IP:port: That is the address and port httpd is bind to send the multicast messages.
This allow to specify an address on multi IP address boxes.

Default: 0.0.0.0:23364

== Minimal Example

Beware of the different names of `mod_cluster_slotmem.so` and `mod_slotmem.so` between mod_cluster 1.3.x and older versions.
Last but not least, pay attention to httpd 2.2.x and httpd 2.4.x authentication configuration changes.

=== mod_cluster 1.3.x, Apache HTTP Server 2.4.x

[source]
----
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so

LoadModule cluster_slotmem_module modules/mod_cluster_slotmem.so

LoadModule manager_module modules/mod_manager.so
LoadModule proxy_cluster_module modules/mod_proxy_cluster.so
LoadModule advertise_module modules/mod_advertise.so

<IfModule manager_module>
  Listen 10.33.144.3:6666
  <VirtualHost 10.33.144.3:6666>

  # Where your worker nodes connect from
  <Location />
     Require ip 127.0.0
  </Location>

  ServerAdvertise On
  EnableMCPMReceive

  # Where administrator reads the console from
  <Location /mod_cluster_manager>
     SetHandler mod_cluster-manager
     Require ip 127.0.0
  </Location>

  </VirtualHost>
</IfModule>
----

=== mod_cluster 1.2.x, Apache HTTP Server 2.2.x

[source]
----
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so

LoadModule slotmem_module modules/mod_slotmem.so

LoadModule manager_module modules/mod_manager.so
LoadModule proxy_cluster_module modules/mod_proxy_cluster.so
LoadModule advertise_module modules/mod_advertise.so

<IfModule manager_module>
  Listen 10.33.144.3:6666
  <VirtualHost 10.33.144.3:6666>

  # Where your worker nodes connect from
  <Location />
     Order deny,allow
     Deny from all
     Allow from 127.0.0.
  </Location>

  ServerAdvertise On
  EnableMCPMReceive

  # Where administrator reads the console from
  <Location /mod_cluster_manager>
     SetHandler mod_cluster-manager
     Order deny,allow
     Deny from all
     Allow from 127.0.0.
  </Location>

  </VirtualHost>
</IfModule>
----

== Building httpd modules

mod_cluster 1.3.x and older, both httpd modules and Tomcat/Wildfly java libraries reside in the https://github.com/modcluster/mod_cluster[mod_cluster] repository, branches 1.3.x and 1.2.x. New development of mod_cluster httpd modules takes place in the new repository: https://github.com/modcluster/mod_proxy_cluster[mod_proxy_cluster].

See https://asciinema.org/a/7563u1eu6o5jlg3a0gk4wv69f?t=52[ASCII recorded tutorial] on httpd modules compilation with your own system httpd.

=== Build with httpd on Windows

We assume you already have a functional Apache HTTP Server on Windows. This example works with Apache Lounge HTTP Server.
We also assume the system has MS Visual Studio (Community Edition is ample) and CMake installed. The example operates in cmder shell, but it is not mandatory. A simple Windows cmd prompt would work too.

 * Download the http://www.apachelounge.com/download/[Apache Lounge distribution]. Our example uses http://www.apachelounge.com/download/VC14/binaries/httpd-2.4.23-win64-VC14.zip[httpd-2.4.23-win64-VC14.zip].
 * unzipped:

[source]
----
C:\Users\karm
ls
httpd-2.4.23-win64-VC14/ httpd-2.4.23-win64-VC14.zip
----

 * Clone mod_proxy_cluster sources git:

[source]
----
git clone https://github.com/modcluster/mod_proxy_cluster.git
----

or download https://github.com/modcluster/mod_proxy_cluster/archive/master.zip[zipped master branch directly].

* Proceed with env vars set and CMake build directory preparation:

[source]
----
C:\Users\karm\mod_proxy_cluster\native (master)
mkdir build

C:\Users\karm\mod_proxy_cluster\native (master)
cd build\

C:\Users\karm\mod_proxy_cluster\native\build (master)
vcvars64.bat
----

Here comes the only slightly tricky part: Apache Lounge httpd ships all necessary *.lib files with exported symbols but for mod_proxy. Since mod_proxy is our dependency, we have to generate these exported symbols from mod_proxy dll.

[source]
----
dumpbin /exports C:\Users\karm\Apache24\modules\mod_proxy.so> C:\Users\karm\Apache24\modules\mod_proxy.exports

echo LIBRARY mod_proxy.so> C:\Users\karm\Apache24\modules\mod_proxy.def

echo EXPORTS>> C:\Users\karm\Apache24\modules\mod_proxy.def

for /f "skip=19 tokens=4" %A in (C:\Users\karm\Apache24\modules\mod_proxy.exports) do echo %A >> C:\Users\karm\Apache24\modules\mod_proxy.def

lib /def:C:\Users\karm\Apache24\modules\mod_proxy.def /OUT:C:\Users\karm\Apache24\modules\mod_proxy.lib /MACHINE:X64 /NAME:mod_proxy.so
----

Let's run CMake:

[source]
----
C:\Users\karm\mod_proxy_cluster\native\build (master)
cmake ../ -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DAPR_LIBRARY=C:\Users\karm\Apache24\lib\libapr-1.lib -DAPR_INCLUDE_DIR=C:\Users\karm\Apache24\include\ -DAPACHE_INCLUDE_DIR=C:\Users\karm\Apache24\include\ -DAPRUTIL_LIBRARY=C:\Users\karm\Apache24\lib\libaprutil-1.lib -DAPRUTIL_INCLUDE_DIR=C:\Users\karm\Apache24\include\ -DAPACHE_LIBRARY=C:\Users\karm\Apache24\lib\libhttpd.lib -DPROXY_LIBRARY=C:\Users\karm\Apache24\modules\mod_proxy.so
-- Found APR: C:/Users/karm/Apache24/lib/libapr-1.lib
-- Found APRUTIL: C:/Users/karm/Apache24/lib/libaprutil-1.lib
-- Found APACHE: C:/Users/karm/Apache24/include
-- Build files have been written to: C:/Users/karm/mod_proxy_cluster/native/build
----

Compile

[source]
----
C:\Users\karm\mod_proxy_cluster\native\build (master)
nmake
----

Directory modules now contains all necessary modules:

[source]
----
C:\Users\karm\mod_proxy_cluster\native\build (master)
cp modules/*.so C:\Users\karm\Apache24\modules\ -v
'modules/mod_advertise.so' -> 'C:/Users/karm/Apache24/modules/mod_advertise.so'
'modules/mod_cluster_slotmem.so' -> 'C:/Users/karm/Apache24/modules/mod_cluster_slotmem.so'
'modules/mod_manager.so' -> 'C:/Users/karm/Apache24/modules/mod_manager.so'
'modules/mod_proxy_cluster.so' -> 'C:/Users/karm/Apache24/modules/mod_proxy_cluster.so'
----

Done.

=== Build httpd from its sources

To build httpd-2.2.x from its sources see http://httpd.apache.org/docs/2.2/install.html[ASF httpd 2.2 doc],
see http://httpd.apache.org/docs/2.4/install.html[ASF httpd 2.4 doc] for httpd-2.4.x.

If needed, patch the httpd-2.2.x sources with (The patch prevents long
waiting time when the node IP can't be resolved that should not happen
so you can skip the patch part if you don't want to rebuild httpd).
https://github.com/modcluster/mod_cluster/blob/master/native/mod_proxy_cluster/mod_proxy_ajp.patch[mod_proxy_ajp.patch]

    (cd modules/proxy
      patch -p0 < $location/mod_proxy_ajp.patch
    )

Configure httpd with something like:

    ./configure  --prefix=apache_installation_directory \
                 --with-mpm=worker \
                 --enable-mods-shared=most \
                 --enable-maintainer-mode \
                 --with-expat=builtin \
                 --enable-ssl \
                 --enable-proxy \
                 --enable-proxy-http \
                 --enable-proxy-ajp \
                 --disable-proxy-balancer

Rebuild (make) and reinstall (make install) after that.

=== Build the 4 modules of mod_cluster

You need an httpd installation with mod_proxy (`--enable-proxy`) and ajp
protocol (`--enable-proxy-ajp`) enabled and with dso enabled (`--enable-so`).

Download the mod_cluster sources:

    git clone git://github.com/modcluster/mod_cluster.git

Build the mod_cluster modules components, for each subdirectory
advertise, mod_manager, mod_proxy_cluster and mod_slotmem do
something like:

[source,bash]
----
sh buildconf
 ./configure --with-apxs=apxs_file_location
 make
 cp *.so apache_installation_directory/modules
----

Where apache_installation_directory is the location of an installed
version of httpd-2-2.x.

NOTE: You can ignore the libtool message on most platform:

[source,bash]
----
libtool: install: warning: remember to run `libtool --finish apache_installation_directory/modules'
----

Once that is done use Apache httpd configuration to configure mod_cluster.

=== Build the mod_proxy module

It is only needed for httpd-2.2.x where x \< 11. Process like the other mod_cluster modules.

== Installing httpd modules

Several bundles are available at http://www.jboss.org/mod_cluster/downloads.html[http://www.jboss.org/mod_cluster/downloads.html].

////
TODO: Amend links. The following article is dated.
////


In case you can't find a prepared package of mod_cluser in the download area, it is possible to build mod_cluster for the sources.
You need a distribution of httpd (at least 2.2.8) or (better) a source tarball of httpd and the sources of mod_cluster.

=== Configuration

////
TODO
////


A minimal configuration is needed in httpd.
A listener must be a added in in JBossWEB conf/server.xml.

==== Installing and using the bundles

The bundles are tar.gz on POSIX platforms just extract them in root something like:

[source,bash]
----
cd /
tar xvf mod-cluster-1.x.y-linux2-x86-ssl.tar.gz
----

The httpd.conf is located in */opt/jboss/httpd/httpd/conf* to quick test
just add something like in the minimal example.

To start httpd do the following:

    httpd/sbin/apachectl start

NOTE: Make sure to use SSL before going in production.


